/*
 * mfcc.c — MFCC Feature Extraction
 *
 * ── What are MFCCs? ───────────────────────────────────────────────────────────
 *
 * MFCC stands for Mel-Frequency Cepstral Coefficients.  They are a compact
 * numerical description of the "shape" of a sound's frequency content at each
 * moment in time.  Speech recognition systems use them because:
 *
 *   1. They closely match how the human ear perceives pitch (the mel scale).
 *   2. They compress a lot of audio into a small matrix (13 × 99 numbers).
 *   3. Different speakers saying the same word produce similar MFCCs even if
 *      the raw waveforms look different.
 *
 * The output of this function is a 2D matrix:
 *   Rows    = 13  MFCC coefficients  (spectral shape at one instant)
 *   Columns = 99  time frames        (one frame ≈ 20 ms of audio)
 *
 * Each column describes what the sound "looks like" in that 20 ms window.
 * The CNN in inference.c learns to recognise the pattern of columns that
 * corresponds to "open sesame".
 *
 * ── How it matches Python ─────────────────────────────────────────────────────
 *
 * The training script uses librosa.feature.mfcc() with these parameters:
 *   sr=8000, n_mfcc=13, n_fft=200, hop_length=160, n_mels=26, center=False
 *
 * This C implementation reproduces that computation exactly using precomputed
 * lookup tables (hann_win, cos_table, sin_table, mel_fb, dct_mat) that were
 * generated by export_weights.py.  If this C code and Python give different
 * numbers, the model weights become invalid for this hardware.
 *
 * ── Three-pass algorithm ──────────────────────────────────────────────────────
 *
 *   Pass 1: For each of the 99 frames:
 *             a. Apply Hann window to the 200-sample frame
 *             b. Compute DFT → 101 power spectrum bins
 *             c. Apply mel filterbank → 26 mel energies
 *             d. Convert to dB with 10 * log10(energy)
 *
 *   Pass 2: Find the global max dB across all frames and mel bands.
 *           Clip anything more than 80 dB below that max.
 *           (This is librosa's top_db=80 normalization.)
 *
 *   Pass 3: Apply the DCT matrix to each frame: 26 mel bands → 13 MFCCs.
 *           Subtract MFCC_MEAN and divide by MFCC_STD (training normalization).
 */

#include "mfcc.h"
#include <math.h>

/* Exact number of samples needed for 99 frames with hop=160 and fft=200.
 * Frame 0 covers samples [0, 199], frame 1 covers [160, 359], …
 * Frame 98 covers [98*160, 98*160+199] = [15680, 15879].
 * So we need sample index 15879, meaning 15880 total samples. */
#define AUDIO_WINDOW_LEN  (N_FFT + HOP_LENGTH * (N_FRAMES - 1))   /* = 15880 */

/* power_to_db constants — must exactly match librosa.power_to_db defaults.
 * AMIN_DB: any mel energy below this is clipped to 1e-10 before log.
 *          Prevents log10(0) = −∞.
 * TOP_DB:  the dynamic range — we clip anything more than 80 dB below peak.
 *          This prevents very quiet frames from having extremely negative values
 *          that would confuse the CNN. */
#define AMIN_DB   1e-10f
#define TOP_DB    80.0f

/*
 * Static scratch buffers — never allocated on the stack.
 *
 * These hold intermediate results during the computation.  Declaring them
 * static means they live in SDRAM for the lifetime of the program.  Putting
 * them on the stack would overflow it (the Nios V stack is ~8 KB; these
 * arrays need ~11 KB total).
 *
 * s_log_mel [26][99]:  log-mel spectrogram — the dB energy in each of the
 *                       26 mel frequency bands for each of the 99 frames.
 *                       This is the intermediate result between the DFT
 *                       step and the DCT step.
 *
 * s_frame   [200]:     one windowed audio frame — the 200 raw samples for
 *                       the current frame after applying the Hann window.
 *
 * s_power   [101]:     DFT power spectrum for the current frame — one value
 *                       per frequency bin (DC to Nyquist = 0 to 4 kHz).
 *
 * s_mel     [26]:      mel filterbank output for the current frame — the
 *                       energy summed within each of the 26 mel bands.
 */
static float s_log_mel[N_MELS][N_FRAMES];
static float s_frame[N_FFT];
static float s_power[N_BINS];
static float s_mel[N_MELS];


/*
 * compute_mfcc — transform a flat audio buffer into a 13×99 MFCC matrix.
 *
 * Parameters:
 *   audio    — pointer to AUDIO_WINDOW_LEN (15880) float samples in [-1.0, 1.0]
 *   mfcc_out — output matrix [N_MFCC][N_FRAMES] = [13][99], normalised
 */
void compute_mfcc(const float *audio, float mfcc_out[N_MFCC][N_FRAMES])
{
    int t, n, k, m, i;

    /* ══════════════════════════════════════════════════════════════════════
     * PASS 1 — compute log-mel energy for every frame
     *
     * We slide a 200-sample window across the audio in steps of 160 samples
     * (= HOP_LENGTH), computing 99 frames total.  For each frame:
     *   Step A: Hann window
     *   Step B: DFT → power spectrum
     *   Step C: Mel filterbank
     *   Step D: power → dB
     * ══════════════════════════════════════════════════════════════════════ */
    for (t = 0; t < N_FRAMES; t++) {

        /* The start sample of this frame in the audio array.
         * Frame 0 starts at 0, frame 1 at 160, frame 2 at 320, … */
        int start = t * HOP_LENGTH;

        /* ── Step A: Apply the Hann window ────────────────────────────────
         *
         * What is a Hann window?
         *   A Hann window is a smooth bell-shaped curve that multiplies the
         *   raw audio samples.  It tapers to zero at both ends of the frame.
         *
         * Why do we need it?
         *   The DFT assumes the signal repeats infinitely.  If a frame starts
         *   and ends at different amplitude values, treating them as a loop
         *   introduces a fake sharp edge.  That edge shows up as high-frequency
         *   noise in the spectrum (called "spectral leakage").
         *   The Hann window eliminates this by gently fading the edges to zero
         *   so there is no discontinuity when the frame "wraps around".
         *
         * hann_win[n] = 0.5 × (1 − cos(2π × n / N_FFT))
         * This was precomputed in export_weights.py and stored in model_data.c. */
        for (n = 0; n < N_FFT; n++)
            s_frame[n] = audio[start + n] * hann_win[n];

        /* ── Step B: Discrete Fourier Transform → power spectrum ──────────
         *
         * What is the DFT?
         *   The DFT converts a time-domain signal (samples over time) into a
         *   frequency-domain representation (how much energy is at each
         *   frequency).  This is exactly what an equaliser visualiser shows.
         *
         * We only compute the POSITIVE frequencies (k = 0 to N_BINS-1 = 101).
         * For a real signal, the negative frequencies are a mirror image of the
         * positive ones — no information is lost by discarding them.
         *
         * For each frequency bin k:
         *   Re[k] = Σ sample[n] × cos(2π × k × n / N_FFT)  (in-phase component)
         *   Im[k] = Σ sample[n] × sin(2π × k × n / N_FFT)  (quadrature component)
         *   Power[k] = Re[k]² + Im[k]²
         *
         * We store Re²+Im² (power spectrum) rather than sqrt(Re²+Im²) (magnitude)
         * because the mel filterbank and log operation that follow don't require
         * the square root, and skipping it saves ~101 sqrt() calls per frame.
         *
         * cos_table[k][n] and sin_table[k][n] were precomputed in
         * export_weights.py to avoid recomputing trig at runtime.
         * (Computing cos/sin on a soft-core RISC-V without FPU is very slow.) */
        for (k = 0; k < N_BINS; k++) {
            float re = 0.0f, im = 0.0f;
            const float *ck = cos_table[k];   /* pointer to row k of cos table */
            const float *sk = sin_table[k];   /* pointer to row k of sin table */
            for (n = 0; n < N_FFT; n++) {
                re += s_frame[n] * ck[n];
                im += s_frame[n] * sk[n];
            }
            s_power[k] = re * re + im * im;   /* power = Re² + Im² */
        }

        /* ── Step C: Mel filterbank ────────────────────────────────────────
         *
         * What is the mel scale?
         *   Human hearing is more sensitive to differences at low frequencies
         *   than at high frequencies.  The mel scale compresses high frequencies
         *   and expands low frequencies to match this perception.
         *   "Mel" comes from the word "melody".
         *
         * The filterbank consists of 26 overlapping triangular filters, each
         * centred at a different mel-scale frequency.  Each filter sums the
         * power spectrum bins within its range, weighted by the triangle shape.
         *
         * Result: 26 mel energies, each representing the total energy in one
         * perceptual frequency band.
         *
         * mel_fb[m][k] is a 26×101 weight matrix precomputed by export_weights.py
         * using librosa.filters.mel().  Each row m is one triangular filter. */
        for (m = 0; m < N_MELS; m++) {
            float e = 0.0f;
            const float *fb = mel_fb[m];   /* pointer to row m of mel filterbank */
            for (k = 0; k < N_BINS; k++)
                e += fb[k] * s_power[k];   /* weighted sum of power bins */
            s_mel[m] = e;
        }

        /* ── Step D: power_to_db (log compression) ─────────────────────────
         *
         * Why log?
         *   Human loudness perception is approximately logarithmic.
         *   A sound that is twice as loud in energy is only slightly louder
         *   to our ears.  Converting to dB (decibels) maps the wide range
         *   of energies (e.g. 0.000001 to 1.0) into a narrower range
         *   (e.g. -100 to 0 dB) that the neural network handles better.
         *
         * Formula: 10 × log10(max(AMIN_DB, mel_energy))
         *   The max() with AMIN_DB (1e-10) prevents log10(0) = −∞.
         *
         * This matches librosa.power_to_db(S, ref=1.0, amin=1e-10). */
        for (m = 0; m < N_MELS; m++) {
            float val = (s_mel[m] < AMIN_DB) ? AMIN_DB : s_mel[m];
            s_log_mel[m][t] = 10.0f * log10f(val);
        }
    }

    /* ══════════════════════════════════════════════════════════════════════
     * PASS 2 — top_db clipping (dynamic range normalisation)
     *
     * After converting to dB, some frames might have extremely low energy
     * (e.g. pure silence = ~-100 dB) while the loudest frame is near 0 dB.
     * This 100 dB dynamic range can destabilise the CNN.
     *
     * We find the global maximum dB value across ALL frames and ALL mel bands,
     * then clip anything more than TOP_DB (80 dB) below it.
     *
     * Example: if the loudest value is -5 dB, the floor becomes -85 dB.
     *          Any value below -85 dB gets set to -85 dB.
     *
     * This matches librosa.power_to_db(..., top_db=80.0).
     * ══════════════════════════════════════════════════════════════════════ */

    /* Find the global maximum across the entire spectrogram */
    float global_max = s_log_mel[0][0];
    for (m = 0; m < N_MELS; m++)
        for (t = 0; t < N_FRAMES; t++)
            if (s_log_mel[m][t] > global_max)
                global_max = s_log_mel[m][t];

    /* Compute the floor and clip */
    float floor_val = global_max - TOP_DB;
    for (m = 0; m < N_MELS; m++)
        for (t = 0; t < N_FRAMES; t++)
            if (s_log_mel[m][t] < floor_val)
                s_log_mel[m][t] = floor_val;

    /* ══════════════════════════════════════════════════════════════════════
     * PASS 3 — DCT and normalisation → final MFCC output
     *
     * What is the DCT?
     *   DCT = Discrete Cosine Transform.  It is similar to a DFT but works
     *   on real numbers only.  Here we use it to convert the 26 log-mel
     *   energies into 13 MFCC coefficients.
     *
     *   Conceptually: the mel filterbank gives us 26 numbers describing the
     *   spectral shape at one frame.  Neighbouring mel bands are correlated
     *   (if band 5 is high, band 6 tends to be high too).  The DCT removes
     *   those correlations and concentrates the most important information
     *   into the first few coefficients.
     *
     *   We keep only the first 13 of the 26 DCT outputs.  The higher
     *   coefficients carry mostly fine-grained spectral detail that is not
     *   useful for speech recognition.
     *
     * Normalisation:
     *   The final step subtracts MFCC_MEAN and divides by MFCC_STD.
     *   These two constants were computed across the entire training dataset
     *   in train_voice_gate.py (mean and std of all MFCC values in all
     *   training clips).  Normalising to zero mean and unit variance makes
     *   the CNN's weight initialisation and gradient descent work better.
     *
     *   IMPORTANT: MFCC_MEAN and MFCC_STD are baked into model_data.h.
     *   If you retrain, export_weights.py regenerates model_data.h with the
     *   new constants.  You must recompile after retraining.
     *
     * dct_mat[i][m] is precomputed in export_weights.py using the ortho-
     * normalised DCT-II basis, matching scipy.fftpack.dct(type=2, norm='ortho')
     * which librosa uses internally.
     * ══════════════════════════════════════════════════════════════════════ */
    for (i = 0; i < N_MFCC; i++) {
        for (t = 0; t < N_FRAMES; t++) {
            /* Compute MFCC coefficient i at time frame t:
             * mfcc[i][t] = Σ_m  dct_mat[i][m] × log_mel[m][t] */
            float val = 0.0f;
            for (m = 0; m < N_MELS; m++)
                val += dct_mat[i][m] * s_log_mel[m][t];

            /* Normalise: subtract training mean, divide by training std.
             * This maps the raw MFCC value to the same scale the CNN saw
             * during training.  Without this, the CNN outputs are garbage. */
            mfcc_out[i][t] = (val - MFCC_MEAN) / MFCC_STD;
        }
    }
}
