/* model_data.h — AUTO-GENERATED by export_weights.py. DO NOT EDIT.
 * Contains extern declarations for all CNN weights and MFCC precomputed tables.
 * Include this header in mfcc.c and inference.c.
 */
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

/* ── MFCC constants ─────────────────────────────────────────────────────── */
#define SAMPLE_RATE   8000
#define N_FFT         200
#define HOP_LENGTH    160
#define N_MELS        26
#define N_MFCC        13
#define N_FRAMES      99
#define N_BINS        101      /* N_FFT/2 + 1 */
#define MFCC_MEAN     -1.15050507e+01f
#define MFCC_STD      5.81032524e+01f
#define LOG_FLOOR     1e-6f

/* ── MFCC precomputed tables ─────────────────────────────────────────────── */
extern const float hann_win[200];
extern const float cos_table[101][200];
extern const float sin_table[101][200];
extern const float mel_fb[26][101];
extern const float dct_mat[13][26];

/* ── CNN weights ─────────────────────────────────────────────────────────── */
/* Conv1: 32 filters, 1 input channel, 3x3 kernel */
extern const float conv1_w[32][1][3][3];
extern const float conv1_b[32];

/* Conv2: 64 filters, 32 input channels, 3x3 kernel */
extern const float conv2_w[64][32][3][3];
extern const float conv2_b[64];

/* Dense1: 4608 inputs → 64 outputs */
extern const float dense1_w[4608][64];
extern const float dense1_b[64];

/* Dense2: 64 inputs → 2 outputs */
extern const float dense2_w[64][2];
extern const float dense2_b[2];

#endif /* MODEL_DATA_H */
